---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/example-image-rectangle/example-image-rectangle.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/3/articles/351136/master/file/figures/example-image-rectangle/example-image-rectangle.png"
    folder_url: "/users/3/articles/351136/master/folder/figures/example-image-rectangle"
